controllers/posts.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from models import Post
from forms import PostForm

posts = Blueprint("posts", __name__)

@posts.route('/posts/new')
def newPost():
  form = PostForm()

  if form.validate_on_submit():
    filename = secure_filename(form.file.data.filename)
    form.file.data.save('uploads/' + filename)
    
    new_post = Post(
      title = form.title.data,
      description = form.description.data,
      media = f'uploads/{filename}',
      score = 0
      #TODO add comments and owner when they are implemented
    )

routes/comments.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from datetime import date, datetime
from models import Comment
from forms import CommentForm
from werkzeug.utils import secure_filename

from extensions import app, db

comments = Blueprint("comments", __name__)


@comments.route('/posts/<post_id>/comments/new', methods=['POST'])
@login_required
def new_comment(post_id):
    """route to create a new comment on a post"""
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment(
            text=form.comment.data,
            created_by=current_user.id,
            attached_to_id=post_id
        )

        db.session.add(new_comment)
        db.session.commit()

        flash('comment added')

    return redirect(url_for('posts.get_post', post_id=post_id))

routes/pages.py
"""Temporary routes for testing frontend"""
from flask import Blueprint, render_template, redirect, url_for
from models import User
from forms import LoginForm

from extensions import db, bcrypt

pages = Blueprint('pages', __name__)


@pages.route('/')
def landing_page():
    """Return landing page"""
    return render_template('index.html')


@pages.route('/browse')
def browse_page():
    """Return browse page"""
    return render_template('browse.html')

routes/posts.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from models import Post, Comment, User
from forms import PostForm, CommentForm
from werkzeug.utils import secure_filename

from extensions import app, db

posts = Blueprint("posts", __name__)


@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        try:
            filename = secure_filename(form.media.data.filename)
            form.file.data.save('uploads/' + filename)
        except AttributeError:
            filename = ''

        new_post = Post(
            title=form.title.data,
            description=form.description.data,
            media=f'uploads/{filename}',
            score=0,
            owner_id=current_user.id
        )

        db.session.add(new_post)
        db.session.commit()

        flash('post added')

        return redirect(url_for('posts.all_posts'))
    return render_template('new_post.html', form=form)


@posts.route('/posts', methods=['GET'])
def all_posts():
    all_posts = Post.query.all()
    return render_template('browse.html', all_posts=all_posts)


@posts.route('/posts/<post_id>', methods=['GET', 'POST'])
def get_post(post_id):
    post = Post.query.get(post_id)
    form = CommentForm()
    comments = db.session.query(User, Post, Comment).filter(
        User.id == Comment.created_by).filter(Post.id == Comment.attached_to_id).all()

    if form.validate_on_submit():
        post.title = form.title.data
        post.description = form.description.data

        try:
            filename = secure_filename(form.media.data.filename)
            form.file.data.save('uploads/' + filename)
        except AttributeError:
            filename = post.media

        post.media = filename

    db.session.commit()

    return render_template('post.html', post=post, form=form, comments=comments)


@posts.route('/posts/delete/<post_id>', methods=['GET'])
@login_required
def delete_post(post_id):

    post = Post.query.get(post_id)

    if post.owner_id == current_user.id:
        db.session.delete(post_id)
        db.session.commit()
    else:
        flash('you are not authorized to delete this')

    return redirect(url_for('posts.all_posts'))

routes/users.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from models import User
from forms import SignupForm, LoginForm

from extensions import db, bcrypt

users = Blueprint('users', __name__)
auth = Blueprint('auth', __name__)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    GET: Returns sign up page
    POST: Creates new user and redirects to all_posts
    """
    form = SignupForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user = User(
            username=form.username.data,
            password=hashed_password
        )

        db.session.add(user)
        db.session.commit()

        login_user(user, remember=True)

        return redirect(url_for('posts.all_posts'))
    return render_template('signup.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """
    GET: Returns sign in page
    Redirect to profile
    """
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            login_user(user, remember=True)
            return redirect(url_for('posts.all_posts'))

    return render_template('signin.html', form=form)


@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('posts.all_posts'))


@users.route('/users/<user_id>', methods=['GET'])
def get_user(user_id):
    user = User.query.get(user_id)

    return render_template('user.html', user=user)


@users.route('/users/delete/<user_id>', methods=['GET'])
@login_required
def delete_user(user_id):
    user = User.query.get(user_id)

    if user.id == current_user.id:
        logout_user()
        db.session.delete(user)
        db.session.commit()

    return redirect(url_for('posts.all_posts'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}planUp-Upgrade Your Teaching Plans{% endblock%}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--BootStrap CDN Link-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
        <!--Custom CSS-->
        <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}"/>
    </head>
    <!--Skeleton/Parent-->
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/browse.html
{% extends 'base.html' %} 
{% block title %} Browse Lesson Plans-planUp {% endblock %} 

{% block content %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container justify-content-center gap-4 container-fluid mt-2">
    <a class="navbar-brand" href="{{ url_for('pages.landing_page') }}"
      >planUp</a
    >
    <!--Navbar items next to brand-->
    <div class="collapse navbar-collapse justify-between flex-grow-0">
      <ul class="navbar-nav">
        <!--Browse Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.browse_page') }}">
            Browse
          </a>
        </li>
        <!--Posts Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.all_posts') }}"> 
            Posts 
          </a>
        </li>
        <!--Buttons-->
        <form class="container container-fluid justify-content-start">
          <!--Sign In Button-->
          <a href="{{ url_for('auth.login') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Login
            </button>
          </a>
          <!--Sign Up Button-->
          <a href="{{ url_for('auth.signup') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Sign Up
            </button>
          </a>
        </form>
      </ul>
    </div>
  </div>
</nav>
<!--End of Navbar-->
<!--Card Section-->
<div class="container container-fluid embed-responsive embed-responsive-16by9 mt-3">
    <div class="row align-items-center">
      {% for post in all_posts %}
          <div class="col-sm-3">
            <div class="card mb-4">
                <video src="https://codingyaar.com/wp-content/uploads/video-in-bootstrap-card.mp4" class="card-img-top" controls></video>
                <div class="card-block card-body">
                    <!-- Card Title -->
                    <h4 class="card-title">{{post.title}}</h4>
                    <!-- Card Text -->
                    <p class="card-text">{{post.description}}</p>
                    <!-- Card Button -->
                    <a href="{{url_for('posts.get_post', post_id=post.id)}}" class="btn btn-primary">Comments</a>
                </div>
            </div>
          </div>
          {% endfor %}
      </div>
  </div>
</div>
<!--End of Card Section-->
<!--Footer-->
<footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top text-center">
  <div class="col mb-3">
    <h5>planUp</h5>
    <p class="text-muted">&copy;2024</p>
  </div>
  <!--Quick Links-->
  <div class="col mb-3">
    <h5>Quick Links</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Home
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a  href="{{ url_for('pages.browse_page') }}" class="nav-link p-0 text-muted text-decoration-none">
          Browse
        </a>
      </li>
      <!--Sign Up-->
      <li class="nav-item mb-2">
        <a href="{{ url_for('auth.signup') }}" class="nav-link p-0 text-muted text-decoration-none">
          Sign Up
        </a>
      </li>
    </ul>
  </div>
  <!--Section 2-->
  <div class="col mb-3">
    <h5>Company</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Careers
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Contact Us
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Our Story
        </a>
      </li>
    </ul>
  </div>
  <!--Section 3-->
  <div class="col mb-3">
    <h5>Support</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          FAQ
        </a>
      </li>
      <!--Resources-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Resources Hub
        </a>
      </li>
      <!--Support-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Support Docs
        </a>
      </li>
    </ul>
  </div>
</footer>
<!--End of Footer Section-->
{% endblock %}

templates/new_post.html
{% extends 'base.html' %} {% block title %}New Post-planUp{% endblock %} {%
block content %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container justify-content-center gap-4 container-fluid mt-2">
    <a class="navbar-brand" href="{{ url_for('pages.landing_page') }}"
      >planUp</a
    >
    <!--Navbar items next to brand-->
    <div class="collapse navbar-collapse flex-grow-0">
      <ul class="navbar-nav">
        <!--Browse Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.browse_page') }}">
            Browse
          </a>
        </li>
        <!--Posts Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.all_posts') }}"
            >New Posts
          </a>
        </li>
        <!--Buttons-->
        <form class="container container-fluid justify-content-start">
          <!--Sign In Button-->
          <a href="{{ url_for('auth.login') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Login
            </button>
          </a>
          <!--Sign Up Button-->
          <a href="{{ url_for('auth.signup') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Sign Up
            </button>
          </a>
        </form>
      </ul>
    </div>
  </div>
</nav>
<!--End of Navbar-->
<!--New Post Section-->
<form class="form-group" action="{{url_for('posts.new_post')}}" method="post">
  {{form.csrf_token}} {{form.title.label}} {{form.title}}

  <ul>
    {% for error in form.title.errors %}
    <li class="text-decoration-none error">{{ error }}</li>
    {% endfor %}
  </ul>

  {{form.description.label}} {{form.description}}

  <ul>
    {% for error in form.description.errors %}
    <li class="text-decoration-none error">{{ error }}</li>
    {% endfor %}
  </ul>

  {{form.media.label}} {{form.media}}

  <ul>
    {% for error in form.media.errors %}
    <li class="text-decoration-none error">{{ error }}</li>
    {% endfor %}
  </ul>

  <input type="submit" value="Submit" />
</form>
<!--End of New Post-->
<!--Footer-->
<footer
  class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top text-center"
>
  <div class="col mb-3">
    <h5>planUp</h5>
    <p class="text-muted">&copy;2024</p>
  </div>
  <!--Quick Links-->
  <div class="col mb-3">
    <h5>Quick Links</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Home
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Browse
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Sign Up
        </a>
      </li>
    </ul>
  </div>
  <!--Section 2-->
  <div class="col mb-3">
    <h5>Company</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Careers
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Contact Us
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Our Story
        </a>
      </li>
    </ul>
  </div>
  <!--Section 3-->
  <div class="col mb-3">
    <h5>Support</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          FAQ
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Resources Hub
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Support Docs
        </a>
      </li>
    </ul>
  </div>
</footer>
<!--End of Footer Section-->
{% endblock %}

templates/post.html
{% extends 'base.html' %} {% block title %} {{post.title}}-planUp {% endblock %}
{{post.title}} {{post.description}} {% block content %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container justify-content-center gap-4 container-fluid mt-2">
    <a class="navbar-brand" href="{{ url_for('pages.landing_page') }}"
      >planUp</a
    >
    <!--Navbar items next to brand-->
    <div class="collapse navbar-collapse flex-grow-0">
      <ul class="navbar-nav">
        <!--Browse Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.browse_page') }}">
            Browse
          </a>
        </li>
        <!--Posts Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.all_posts') }}">
            New Posts
          </a>
        </li>
        <!--Buttons-->
        <form class="container container-fluid justify-content-start">
          <!--Sign In Button-->
          <a href="{{ url_for('auth.login') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Login
            </button>
          </a>
          <!--Sign Up Button-->
          <a href="#">
            <button class="btn btn-outline-success me-2" type="button">
              Profile
            </button>
          </a>
        </form>
      </ul>
    </div>
  </div>
</nav>
<!--End of Navbar-->
<!--Comment Section-->
<div class="container container-fluid mt-5 mb-5">
  <div class="row height d-flex justify-content-center align-items-center">
    <div class="col-md-7">
      <div class="card">
        <div class="p-3">
          <h6>Comments</h6>
        </div>
        <form
          class="form-group"
          action="{{url_for('comments.new_comment', post_id=post.id)}}"
          method="POST"
        >
          {{form.csrf_token}} {{form.comment.label}} {{form.comment}}

          <ul>
            {% for error in form.comment.errors %}
            <li class="text-decoration-none error">{{ error }}</li>
            {% endfor %}
          </ul>

          <input type="submit" value="Submit" />
        </form>
        <div class="mt-2">
          {% for comment in comments %}
          <div class="d-flex flex-row p-3">
            <!--Profile Picture-->
            <img
              src="https://fakeimg.pl/40x40"
              width="40"
              height="40"
              class="rounded-circle mr-3"
            />
            <div class="w-100">
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex flex-row align-items-center">
                  <!--Profile Name-->
                  <span class="mr-2">{{comment.User.username}}</span>
                </div>
                <!--Time Created-->
                <small>12h ago</small>
              </div>
              <!--Comment-->
              <p class="text-justify comment-text mb-0">
                {{comment.Comment.text}}
              </p>
            </div>
          </div>
          {%endfor%}
        </div>
      </div>
    </div>
  </div>
</div>
<!--End of Comment Section-->
<!--Start of Post form-->

<!--End of Post Form-->
<!--Footer-->
<footer
  class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top text-center"
>
  <div class="col mb-3">
    <h5>planUp</h5>
    <p class="text-muted">&copy;2024</p>
  </div>
  <!--Quick Links-->
  <div class="col mb-3">
    <h5>Quick Links</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Home
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a
          href="{{ url_for('pages.browse_page') }}"
          class="nav-link p-0 text-muted text-decoration-none"
        >
          Browse
        </a>
      </li>
      <!--Sign Up-->
      <li class="nav-item mb-2">
        <a
          href="{{ url_for('auth.signup') }}"
          class="nav-link p-0 text-muted text-decoration-none"
        >
          Sign Up
        </a>
      </li>
    </ul>
  </div>
  <!--Section 2-->
  <div class="col mb-3">
    <h5>Company</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Careers
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Contact Us
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Our Story
        </a>
      </li>
    </ul>
  </div>
  <!--Section 3-->
  <div class="col mb-3">
    <h5>Support</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          FAQ
        </a>
      </li>
      <!--Resources-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Resources Hub
        </a>
      </li>
      <!--Support-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Support Docs
        </a>
      </li>
    </ul>
  </div>
</footer>
<!--End of Footer Section-->
{% endblock %}

templates/signin.html
{% extends 'base.html' %} {% block title %} Sign In-planUp {% endblock %}

<!--Sign In Page-->
{% block content %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container justify-content-center gap-4 container-fluid mt-2">
    <a class="navbar-brand" href="{{ url_for('pages.landing_page') }}"
      >planUp</a
    >
    <!--Navbar items next to brand-->
    <div class="collapse navbar-collapse flex-grow-0">
      <ul class="navbar-nav">
        <!--Browse Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('pages.browse_page') }}">
            Browse
          </a>
        </li>
        <!--Posts Link-->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.all_posts') }}"> Posts </a>
        </li>
        <!--Buttons-->
        <form class="container container-fluid justify-content-start">
          <!--Sign In Button-->
          <a href="{{ url_for('auth.login') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Login
            </button>
          </a>
          <!--Sign Up Button-->
          <a href="{{ url_for('auth.signup') }}">
            <button class="btn btn-outline-success me-2" type="button">
              Sign Up
            </button>
          </a>
        </form>
      </ul>
    </div>
  </div>
</nav>
<!--End of Navbar-->
<!--Sign In Form-->
<div class="container container-fluid">
  <h2 class="h2 text-center mt-4 mb-4">Sign In</h2>
  <form method="post" action="{{ url_for('auth.login')}}" class="form-group">
    {{ form.csrf_token }}
    <div class="mb-3 row text-center">
      <div class="col-sm-10">
        <label class="col-form-label">{{ form.username.label }}:</label>
        {{ form.username }}
        <label class="col-form-label">{{ form.password.label }}:</label>
        {{ form.password }}
        <!--Submit-->
        <button class="btn">{{ form.submit }}Submit</button>
      </div>
      <a href="{{ url_for('auth.signup') }}" class="mr-2 mt-3"
        >Need an account?</a
      >
    </div>
  </form>
</div>
<!--End of Sign In Form-->
<!--Footer-->
<footer
  class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top text-center"
>
  <div class="col mb-3">
    <h5>planUp</h5>
    <p class="text-muted">&copy;2024</p>
  </div>
  <!--Quick Links-->
  <div class="col mb-3">
    <h5>Quick Links</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Home
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a
          href="{{ url_for('pages.browse_page') }}"
          class="nav-link p-0 text-muted text-decoration-none"
        >
          Browse
        </a>
      </li>
      <!--Sign Up-->
      <li class="nav-item mb-2">
        <a
          href="{{ url_for('auth.signup') }}"
          class="nav-link p-0 text-muted text-decoration-none"
        >
          Sign Up
        </a>
      </li>
    </ul>
  </div>
  <!--Section 2-->
  <div class="col mb-3">
    <h5>Company</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Careers
        </a>
      </li>
      <!--Browse-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Contact Us
        </a>
      </li>
      <!--Our Story/About-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Our Story
        </a>
      </li>
    </ul>
  </div>
  <!--Section 3-->
  <div class="col mb-3">
    <h5>Support</h5>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          FAQ
        </a>
      </li>
      <!--Resources-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Resources Hub
        </a>
      </li>
      <!--Support Docs-->
      <li class="nav-item mb-2">
        <a href="#" class="nav-link p-0 text-muted text-decoration-none">
          Support Docs
        </a>
      </li>
    </ul>
  </div>
</footer>
<!--End of Footer Section-->
{% endblock %}